### PR TITLE
improvments; * add line numbering, updated examples and hint to typing

### PR DESCRIPTION
**Pull request by drtrigon**

### CODE REVIEW

**Comment by drtrigon** [comment]
Ahhh sorry just recognized it does NOT work for >10 lines and scrolling. May be forget about this.

**Comment by drtrigon** [comment]
Ok better:
* scrolling work now
* there is not enough space for 2 digits, so I just display the last one (so "10", "20", etc. are "0" / "11", "21", etc. are "1" / etc.)

Nice would be to use smaller numbers than the code text, but then the line spacing is not correct anymore as I use just 1 multi-line text label.

**Comment by drtrigon** [comment]
It is based on very simple keyword list and rudimentary syntax checking. I did not find a way to remove styles set, so the only good way to update syntax highlighting is by closing the editor window and re-opening.

**Comment by bilderbuchi** [comment]
Tbh, I personally would try to use an established/maintain editor component (like scintilla or somesuch) instead of trying to implement all these features (copy paste, line numbers, syntax highlight) myself, which is a huge amount of work to implement correctly/generally usable...

**Comment by honix** [comment]
@bilderbuchi what about this: pyno file is a nodes position and connection data, along with pyno file you have folder with files for each node. This files contains code for nodes.

Like this:
image

Idea is to use any code editor you like, and hook file saving to reload the code. We got nodes folder, and simplify our project to just pyno engine with patch editor.

**Comment by drtrigon** [comment]
What about a split screen editor e.g. left side patch editor, right side according python script. This needs a way of clearly assign node to script parts (function) and vice versa. It also needs a way of auto generate and insert code on node creation (and may be vice versa).

**Comment by honix** [comment]
@drtrigon look, by splitting patches and nodes, we can start create a library of those. I think it is good turn.

I like how pyno's code editor looks like now and i like its form and postion around the node, only question, can we bring cool features in it. Really i think we can. It is already pretty awesome thanks to @drtrigon! :)

**Comment by honix** [comment]
If we do split patches and nodes, user can edit node with editor he like or just use pyno's editor.

**Comment by drtrigon** [comment]
I was reasoning in direction of simplicity to use (and understand)... but it seems I do not fully get your idea - however sounds interesting ... so I'll wait for first working examples in order to get the concept... ;) Thanks for your work!

**Pull request merged**
